$ErrorActionPreference = "Stop"
Set-Location $PSScriptRoot

$prefsPath = Join-Path $PSScriptRoot "data\localai.properties"
$backupPath = Join-Path $PSScriptRoot "data\localai.properties.lifefeel.bak"

function Save-BackupIfNeeded {
    if (Test-Path $prefsPath) {
        Copy-Item -Path $prefsPath -Destination $backupPath -Force
    } elseif (Test-Path $backupPath) {
        Remove-Item -Path $backupPath -Force
    }
}

function Restore-Backup {
    if (Test-Path $backupPath) {
        Copy-Item -Path $backupPath -Destination $prefsPath -Force
        Remove-Item -Path $backupPath -Force
    } elseif (Test-Path $prefsPath) {
        Remove-Item -Path $prefsPath -Force
    }
}

function Set-LatencyProfile([string]$profile) {
    $props = @{}
    if (Test-Path $prefsPath) {
        foreach ($line in (Get-Content -Path $prefsPath -Encoding UTF8)) {
            $ln = [string]$line
            if ([string]::IsNullOrWhiteSpace($ln) -or $ln.StartsWith("#")) { continue }
            $eq = $ln.IndexOf("=")
            if ($eq -lt 1) { continue }
            $k = $ln.Substring(0, $eq).Trim()
            $v = $ln.Substring($eq + 1).Trim()
            if (-not [string]::IsNullOrWhiteSpace($k)) {
                $props[$k] = $v
            }
        }
    }
    $props["latencyProfile"] = $profile
    if (-not $props.ContainsKey("baseUrl")) { $props["baseUrl"] = "http://127.0.0.1:1234" }
    if (-not $props.ContainsKey("model")) { $props["model"] = "google/gemma-4-e4b" }
    New-Item -ItemType Directory -Force -Path (Split-Path $prefsPath -Parent) | Out-Null
    $rows = @("# LovingAI local LLM prefs (generated by verify-lifefeel.ps1)")
    foreach ($k in ($props.Keys | Sort-Object)) {
        $rows += "$k=$($props[$k])"
    }
    Set-Content -Path $prefsPath -Value $rows -Encoding UTF8
}

Save-BackupIfNeeded
try {
    foreach ($profile in @("fast", "balanced", "deep")) {
        Write-Host "=== verify profile: $profile ===" -ForegroundColor Cyan
        Set-LatencyProfile $profile
        $existing = $null
        try {
            $existing = Get-NetTCPConnection -LocalPort 8080 -State Listen -ErrorAction SilentlyContinue
        } catch {
            $existing = $null
        }
        if ($existing) {
            Write-Host "WARN: 8080 already occupied, run compile-only check for $profile" -ForegroundColor Yellow
            & .\compile.ps1 | Out-Host
        } else {
            & .\verify-smoke.ps1 | Out-Host
            & .\verify-regression.ps1 | Out-Host
            & .\verify-contracts.ps1 | Out-Host
        }
    }
    Write-Host "OK: life-feel regression passed on fast/balanced/deep." -ForegroundColor Green
} finally {
    Restore-Backup
}
